### ISSUE TITLE
关于不定时出现的EGL_NOT_INITIALIZED报错导致app崩溃问题

### ISSUE THREAD

**Issue by dpmaycry** [ChillingVan/android-openGL-canvas#30]
有2种报错日志，都跟egl未被初始化有关
1:
-------------------------------------------------------------------------------------------
E/GLConsumer( 3229): [unnamed-3229-1] syncForReleaseLocked: error creating EGL fence: 0x3001
E/DefaultContextFactory( 3229): display:android.opengl.EGLDisplay@210 context: android.opengl.EGLContext@46bd535e
--------- beginning of crash
E/AndroidRuntime( 3229): FATAL EXCEPTION: GLThread 237
E/AndroidRuntime( 3229): Process: com.dp.test, PID: 3229
E/AndroidRuntime( 3229): java.lang.RuntimeException: eglDestroyContext failed: EGL_NOT_INITIALIZED
E/AndroidRuntime( 3229):        at com.chillingvan.canvasgl.glview.texture.gles.EglHelper.throwEglException(EglHelper.java:226)
E/AndroidRuntime( 3229):        at com.chillingvan.canvasgl.glview.texture.gles.GLThread$DefaultContextFactory.destroyContext(GLThread.java:994)
E/AndroidRuntime( 3229):        at com.chillingvan.canvasgl.glview.texture.gles.EglHelperAPI17.finish(EglHelperAPI17.java:159)
E/AndroidRuntime( 3229):        at com.chillingvan.canvasgl.glview.texture.gles.GLThread.stopEglContextLocked(GLThread.java:163)
E/AndroidRuntime( 3229):        at com.chillingvan.canvasgl.glview.texture.gles.GLThread.guardedRun(GLThread.java:445)
E/AndroidRuntime( 3229):        at com.chillingvan.canvasgl.glview.texture.gles.GLThread.run(GLThread.java:132)
F/libc    ( 3229): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 3396 (faceRect)
2：
-------------------------------------------------------------------------------------------
F/OpenGLRenderer( 3229): Failed to create EGLSurface for window 0xb950c000, eglErr = EGL_NOT_INITIALIZED
F/libc    ( 3229): Fatal signal 6 (SIGABRT), code -6 in tid 3247 (RenderThread)
E/DEBUG   (  224): Failed to find a valid tombstone, default to using tombstone 0.

**Comment by ChillingVan** [comment]
我试试写个Camera2的例子吧

**Comment by dpmaycry** [comment]
这个跟camera2无关，我用camera1也这样，只是时间要长点

**Comment by ChillingVan** [comment]
@dpmaycry 我尝试了一下，发现只熄屏的时候会卡住，表现和你的不同。但是不熄屏的时候30分钟也没问题。你长时间放时，屏幕有没有熄灭？
