### ISSUE TITLE
Bitmaps drawn on canvas stay in graphics memory and throw out of memory error.

### ISSUE THREAD

**Issue by sumitatcs** [ChillingVan/android-openGL-canvas#37]
Is there a way to free memory taken by the uploaded texture after it has been drawn or reuse the texture and just update with new bitmap data if the bitmaps are of same size? Drawing multiple bitmaps over camera preview results in out of memory error.

**Comment by sumitatcs** [comment]
No. I encounter out of memory error when drawing bitmaps over camera preview.

<sharedmem_gpumem_alloc_id:2255>: sharedmem_gpumem_alloc: mmap failed errno 12 Out of memory
/Adreno-GSL: <gsl_memory_alloc_pure:1971>: GSL MEM ERROR: kgsl_sharedmem_alloc ioctl failed.
/Adreno-ES20: <core_glTexSubImage2D:562>: GL_OUT_OF_MEMORY
/GLES20Canvas: GL error: 1285
    java.lang.Throwable
        at com.chillingvan.canvasgl.glcanvas.GLES20Canvas.checkError(GLES20Canvas.java:981)
        at com.chillingvan.canvasgl.glcanvas.GLES20Canvas.texSubImage2D(GLES20Canvas.java:952)
        at com.chillingvan.canvasgl.glcanvas.UploadedTexture.uploadToCanvas(UploadedTexture.java:255)
        at com.chillingvan.canvasgl.glcanvas.UploadedTexture.updateContent(UploadedTexture.java:195)
        at com.chillingvan.canvasgl.glcanvas.UploadedTexture.onBind(UploadedTexture.java:279)
        at com.chillingvan.canvasgl.glcanvas.GLES20Canvas.prepareTexture(GLES20Canvas.java:676)
        at com.chillingvan.canvasgl.glcanvas.GLES20Canvas.prepareTexture(GLES20Canvas.java:666)
        at com.chillingvan.canvasgl.glcanvas.GLES20Canvas.drawTextureRect(GLES20Canvas.java:634)
        at com.chillingvan.canvasgl.glcanvas.GLES20Canvas.drawTextureRect(GLES20Canvas.java:619)
        at com.chillingvan.canvasgl.glcanvas.GLES20Canvas.drawTexture(GLES20Canvas.java:589)
        at com.chillingvan.canvasgl.CanvasGL.drawBitmap(CanvasGL.java:188)
        at com.chillingvan.canvasgl.CanvasGL.drawBitmap(CanvasGL.java:182)

Do i need to retain the bitmap reference and use same reference for each bitmap? (Doing this doesn't actually solve this out of memory issue).

**Comment by ChillingVan** [comment]
@sumitatcs  Did you encount this error when you use the sample TextureCameraActivity? If not, please check whether the sample is fine.
And when you pass the bitmap to GLCanvas, it will bind to a texture. When the texture is not used and detected by GC, it will be recycled and won't reference the bitmap anymore.
But this library won't call bitmap.recycle. So you must make sure your bitmap is recycled.

You can check the code CanvasGL, it just use a WeakHashMap to refer the textures.
